# Generated by Django 4.0.4 on 2022-06-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(blank=True, max_length=64, verbose_name='first name')),
                ('lastName', models.CharField(blank=True, max_length=64, verbose_name='last name')),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='avatar')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='gender')),
                ('totalPoints', models.FloatField(default=0, verbose_name='total rate points')),
                ('turns', models.IntegerField(default=0, verbose_name='rate turns')),
                ('experienceYears', models.FloatField(default=0, verbose_name='experience years')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
