# Generated by Django 4.0.4 on 2022-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
    ]
