# Generated by Django 4.0.4 on 2022-09-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(verbose_name='working time in day')),
                ('weekday', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], verbose_name='weekday')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='doctor.doctor')),
            ],
            options={
                'db_table': 'working_shift',
            },
        ),
    ]
