# Generated by Django 4.0.4 on 2022-09-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_workingshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='active shift'),
        ),
    ]
