# Generated by Django 4.0.4 on 2022-09-09 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_workingshift_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingshift',
            name='time',
        ),
        migrations.AddField(
            model_name='workingshift',
            name='endTime',
            field=models.TimeField(default=datetime.time(17, 30), verbose_name='end time in weekday'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='startTime',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='start time in weekday'),
        ),
    ]
