# Generated by Django 4.0.4 on 2022-09-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_workingshift_time_workingshift_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='package name')),
                ('description', models.CharField(max_length=255, verbose_name='package description')),
                ('price', models.IntegerField(verbose_name='package price')),
                ('commissionPercent', models.FloatField(default=0.2, verbose_name='commission')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='doctor.doctor')),
            ],
            options={
                'db_table': 'package',
            },
        ),
    ]
