# Generated by Django 4.0.4 on 2022-10-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='isApproved',
            field=models.BooleanField(default=False, verbose_name='is approved'),
        ),
        migrations.AddField(
            model_name='package',
            name='isOnline',
            field=models.BooleanField(default=False, verbose_name='is online'),
        ),
    ]
