# Generated by Django 4.0.4 on 2022-10-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_package_category'),
        ('doctor', '0011_package_isapproved_package_isonline'),
    ]

    operations = [
    ]
