# Generated by Django 4.0.4 on 2022-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_merge_20221006_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('AT_DOCTOR_HOME', 'At Doctor Home'), ('AT_PATIENT_HOME', 'At Patient Home'), ('ONLINE', 'Online')], max_length=20, verbose_name='category'),
        ),
    ]
