# Generated by Django 4.0.4 on 2022-10-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_merge_20221004_2313'),
        ('doctor', '0013_alter_package_category'),
    ]

    operations = [
    ]
