# Generated by Django 4.1.2 on 2022-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_merge_20221013_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='isApproved',
            field=models.BooleanField(default=True, verbose_name='is approved'),
        ),
    ]
