# Generated by Django 4.1.2 on 2022-12-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_alter_package_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='firstName',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastName',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='last name'),
        ),
    ]
