# Generated by Django 4.0.4 on 2022-07-30 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(blank=True, max_length=64, verbose_name='first name')),
                ('lastName', models.CharField(blank=True, max_length=64, verbose_name='last name')),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='gender')),
                ('avatar', models.CharField(blank=True, max_length=255, verbose_name='avatar')),
                ('old_health_records', models.JSONField(null=True, verbose_name='old health records')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
