# Generated by Django 4.0.4 on 2022-09-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_workingshift_time_workingshift_endtime_and_more'),
        ('appointment', '0007_remove_packagemeta_duration_delete_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemeta',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_metas', to='doctor.doctor'),
        ),
    ]
