# Generated by Django 4.0.4 on 2022-09-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_workingshift_time_workingshift_endtime_and_more'),
        ('appointment', '0008_packagemeta_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
                ('estEndAt', models.DateTimeField(null=True, verbose_name='estimate end at')),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointment.appointment')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to='doctor.workingshift')),
            ],
            options={
                'db_table': 'scheduled_appointment',
            },
        ),
    ]
