# Generated by Django 4.0.4 on 2022-09-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_scheduledappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledappointment',
            name='bookedAt',
            field=models.DateTimeField(null=True, verbose_name='booked at'),
        ),
    ]
