# Generated by Django 4.0.4 on 2022-09-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_scheduledappointment_bookedat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledAppointment',
        ),
    ]
