# Generated by Django 4.0.4 on 2022-09-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_delete_scheduledappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemeta',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='packagemeta',
            name='package',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='package_meta',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageMeta',
        ),
    ]
