# Generated by Django 4.0.4 on 2022-09-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_package_price'),
        ('appointment', '0012_remove_packagemeta_doctor_remove_packagemeta_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='doctor.package'),
        ),
    ]
