# Generated by Django 4.0.4 on 2022-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_appointment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isSystemCancelled',
            field=models.BooleanField(default=False, verbose_name='system cancelled'),
        ),
    ]
