# Generated by Django 4.1.2 on 2022-11-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_method_alter_service_description'),
        ('appointment', '0015_remove_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='package',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='service.service'),
        ),
    ]
