# Generated by Django 4.0.4 on 2022-12-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0015_alter_package_isapproved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('date', models.DateField(verbose_name='day of week')),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='end')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slots', to='doctor.doctor')),
            ],
            options={
                'db_table': 'doctor_slots',
            },
        ),
    ]
