# Generated by Django 4.0.4 on 2022-12-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='status',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('AVAILABLE', 'Available'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=20, verbose_name='status'),
        ),
    ]
