# Generated by Django 4.0.4 on 2022-09-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('doctor', '0008_remove_workingshift_time_workingshift_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bookedAt', models.DateTimeField(null=True, verbose_name='booked at')),
                ('estEndAt', models.DateTimeField(null=True, verbose_name='estimate end at')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('SESSION', 'Session'), ('APPOINTMENT', 'Appointment')], max_length=15, null=True, verbose_name='schedule type')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctor.doctor')),
            ],
            options={
                'db_table': 'schedule',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
