# Generated by Django 4.0.4 on 2022-08-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0004_specification'),
        ('treatment', '0002_treatmentcontract'),
        ('health_record', '0001_initial'),
        ('patient', '0002_alter_patient_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='treatment.treatmentcontract'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_records', to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_records', to='patient.patient'),
        ),
    ]
