# Generated by Django 4.0.4 on 2022-08-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_supervisor'),
        ('health_record', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='ICD_10_code')),
                ('name', models.CharField(max_length=255, verbose_name='disease name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='disease description')),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='symptom title')),
                ('shortDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='short description about symptom')),
                ('healthRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='health_record.healthrecord')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='patient.patient')),
            ],
            options={
                'db_table': 'symptom',
            },
        ),
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='health_record.disease')),
                ('healthRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='health_record.healthrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
