# Generated by Django 4.0.4 on 2022-08-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0003_disease_symptom_diagnose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnose',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
