# Generated by Django 4.0.4 on 2022-10-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_supervisor'),
        ('doctor', '0011_package_category'),
        ('health_record', '0004_delete_diagnose_delete_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('historyOfPresentIllness', models.JSONField(verbose_name='history of present Illness')),
                ('medicationHistory', models.JSONField(verbose_name='medication history')),
                ('socialHistory', models.JSONField(verbose_name='social history')),
                ('allergies', models.JSONField(verbose_name='allergies')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_patient_health_records', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_health_records', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('chiefComplaint', models.CharField(max_length=255, verbose_name='chief complaint')),
                ('historyOfPresentIllness', models.JSONField(verbose_name='history of present illness')),
                ('medicationHistory', models.JSONField(verbose_name='medication history')),
                ('socialHistory', models.JSONField(verbose_name='social history')),
                ('allergies', models.JSONField(verbose_name='allergies')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_history', to='patient.patient')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_history', to='health_record.patienthealthrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
