# Generated by Django 4.0.4 on 2022-10-07 07:57

from django.db import migrations, models
import health_record.models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0004_delete_diagnose_delete_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='detail',
            field=models.JSONField(default=health_record.models._get_default_value, verbose_name='health record detail'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='historical',
            field=models.JSONField(default=health_record.models._get_default_value, verbose_name='historical detail'),
        ),
    ]
