# Generated by Django 4.0.4 on 2022-10-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_supervisor'),
        ('health_record', '0006_remove_patientmedicalhistory_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('chiefComplaint', models.CharField(max_length=255, verbose_name='chief complaint')),
                ('historyOfPresentIllness', models.JSONField(verbose_name='history of present illness')),
                ('medicationHistory', models.JSONField(verbose_name='medication history')),
                ('socialHistory', models.JSONField(verbose_name='social history')),
                ('allergies', models.JSONField(verbose_name='allergies')),
                ('healthRecord', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_medical_history', to='health_record.healthrecord')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_history', to='patient.patient')),
            ],
            options={
                'db_table': 'patient_medical_history',
            },
        ),
    ]
