# Generated by Django 4.0.4 on 2022-10-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0005_healthrecord_detail_healthrecord_historical'),
        ('health_record', '0007_patientmedicalhistory'),
    ]

    operations = [
    ]
