# Generated by Django 4.1.2 on 2022-10-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0009_delete_patientmedicalhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
