# Generated by Django 4.0.4 on 2022-10-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_package_category'),
        ('patient', '0002_alter_patient_supervisor'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnose',
            field=models.JSONField(null=True, verbose_name='diagnose'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patient.patient'),
        ),
    ]
