# Generated by Django 4.0.4 on 2022-10-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescription_diagnose_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='cancelReason',
            field=models.CharField(max_length=255, null=True, verbose_name='cancelReason'),
        ),
    ]
