# Generated by Django 4.0.4 on 2022-10-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_prescription_cancelreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='fromDate',
            field=models.DateField(null=True, verbose_name='from_date'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='toDate',
            field=models.DateField(null=True, verbose_name='to_date'),
        ),
    ]
