# Generated by Django 4.1.2 on 2022-12-07 10:18

from django.db import migrations, models
import prescription.models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_prescription_fromdate_prescription_todate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='note',
            field=models.JSONField(default=prescription.models._getDefaultValue, verbose_name='note'),
        ),
    ]
