# Generated by Django 4.0.4 on 2022-12-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_prescription_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='unit',
            field=models.CharField(max_length=30, null=True, verbose_name='unit'),
        ),
    ]
