# Generated by Django 4.0.4 on 2022-08-01 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_specification'),
        ('patient', '0002_alter_patient_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('POSTPONE', 'Postpone')], default='PENDING', max_length=15, verbose_name='contract status')),
                ('cancelReason', models.CharField(blank=True, max_length=255, null=True, verbose_name='cancellation reason')),
                ('startedAt', models.DateTimeField(null=True, verbose_name='started date')),
                ('endedAt', models.DateTimeField(null=True, verbose_name='ended date')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='patient.patient')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_contract',
            },
        ),
    ]
