# Generated by Django 4.0.4 on 2022-08-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_treatmentcontract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
