# Generated by Django 4.0.4 on 2022-10-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_package_category'),
        ('treatment', '0003_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcontract',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='doctor.package'),
        ),
    ]
