# Generated by Django 4.1.2 on 2022-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_treatmentcontract_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentcontract',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('POSTPONE', 'Postpone')], default='PENDING', max_length=15, verbose_name='contract status'),
        ),
    ]
