# Generated by Django 4.1.2 on 2022-11-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_category'),
        ('treatment', '0006_treatmentsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcontract',
            name='package',
        ),
        migrations.AddField(
            model_name='treatmentcontract',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='service.service'),
        ),
    ]
