# Generated by Django 4.0.4 on 2022-11-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0007_remove_treatmentcontract_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='checkInCode',
            field=models.CharField(default='123456', max_length=255, verbose_name='Check in code'),
        ),
        migrations.AlterField(
            model_name='treatmentcontract',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('POSTPONE', 'Postpone')], default='PENDING', max_length=20, verbose_name='contract status'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_sessions', to='treatment.treatmentcontract'),
        ),
        migrations.AlterModelTable(
            name='treatmentsession',
            table='treatment_sessions',
        ),
        migrations.AddField(
            model_name='treatmentcontract',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='service.service'),
        ),
    ]
