# Generated by Django 4.0.4 on 2022-11-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_treatmentsession_checkincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcontract',
            name='isDoctorCancelled',
            field=models.BooleanField(default=False, verbose_name='Is_Supervisor_Cancel'),
        ),
        migrations.AddField(
            model_name='treatmentcontract',
            name='isSupervisorCancelled',
            field=models.BooleanField(default=False, verbose_name='Is_Supervisor_Cancel'),
        ),
        migrations.AddField(
            model_name='treatmentcontract',
            name='isSystemCancelled',
            field=models.BooleanField(default=False, verbose_name='Is_Supervisor_Cancel'),
        ),
    ]
