# Generated by Django 4.0.4 on 2022-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_treatmentcontract_isdoctorcancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentcontract',
            name='isDoctorCancelled',
            field=models.BooleanField(default=False, verbose_name='Is_Doctor_Cancel'),
        ),
        migrations.AlterField(
            model_name='treatmentcontract',
            name='isSystemCancelled',
            field=models.BooleanField(default=False, verbose_name='Is_System_Cancel'),
        ),
    ]
