# Generated by Django 4.0.4 on 2022-12-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
        ('slot', '0002_alter_doctorslot_status'),
        ('treatment', '0010_alter_treatmentcontract_isdoctorcancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatment_sessions', to='slot.doctorslot'),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=255, verbose_name='Status'),
        ),
    ]
