# Generated by Django 4.0.4 on 2022-12-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0011_treatmentsession_slot_treatmentsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='supervisor',
        ),
    ]
