# Generated by Django 4.1.2 on 2022-12-07 10:18

from django.db import migrations, models
import treatment.models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0017_treatmentsession_cancelreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentsession',
            name='assessment',
            field=models.JSONField(default=treatment.models._get_default_value, verbose_name='assessment'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='note',
            field=models.JSONField(default=treatment.models._get_default_value, verbose_name='note'),
        ),
    ]
