# Generated by Django 4.0.4 on 2022-12-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0017_treatmentsession_cancelreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='endTime',
            field=models.DateTimeField(null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='startTime',
            field=models.DateTimeField(null=True, verbose_name='start time'),
        ),
    ]
