# Generated by Django 4.0.4 on 2022-12-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0018_treatmentsession_endtime_treatmentsession_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='slot',
        ),
    ]
