# Generated by Django 4.0.4 on 2022-12-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0018_alter_treatmentsession_assessment_and_more'),
        ('treatment', '0019_remove_treatmentsession_slot'),
    ]

    operations = [
    ]
