# Generated by Django 4.0.4 on 2022-08-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_record', '0004_delete_diagnose_delete_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('otherCode', models.CharField(max_length=10, verbose_name='other code')),
                ('generalName', models.CharField(max_length=255, verbose_name='general name')),
                ('vGeneralName', models.CharField(max_length=255, verbose_name='vietnamese general name')),
                ('diseaseName', models.CharField(max_length=255, verbose_name='disease name')),
                ('vDiseaseName', models.CharField(max_length=255, verbose_name='vietnamese disease name')),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500, verbose_name='diagnose description')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='disease.disease')),
                ('healthRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='health_record.healthrecord')),
            ],
            options={
                'db_table': 'disease_diagnose',
            },
        ),
    ]
