# Generated by Django 4.0.4 on 2022-08-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_alter_disease_code_alter_disease_diseasename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='code',
            field=models.CharField(max_length=255, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='otherCode',
            field=models.CharField(max_length=255, null=True, verbose_name='other code'),
        ),
    ]
