# Generated by Django 4.1.2 on 2022-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0002_alter_medicalinstruction_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinstruction',
            name='submissions',
            field=models.JSONField(null=True, verbose_name='submissions'),
        ),
    ]
