# Generated by Django 4.0.4 on 2022-06-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
