# Generated by Django 4.0.4 on 2022-06-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_isapproved'),
        ('user', '0006_user_avatar_user_dob_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='account', to='doctor.doctor'),
        ),
    ]
