# Generated by Django 4.0.4 on 2022-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='googleId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='google id'),
        ),
    ]
