# Generated by Django 4.0.4 on 2022-10-12 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warn')], default='INFO', max_length=10)),
                ('isRead', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('payload', models.JSONField(blank=True, default=user.models._get_default_dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
