# Generated by Django 4.1.2 on 2022-11-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('MANAGER', 'Manager')], default='MEMBER', max_length=10, verbose_name='user type'),
        ),
    ]
