# Generated by Django 4.1.2 on 2022-11-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mainBalance',
            field=models.FloatField(default=0.0, verbose_name='main balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='tempBalance',
            field=models.FloatField(default=0.0, verbose_name='temp balance'),
        ),
    ]
