# Generated by Django 4.1.2 on 2022-11-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_doctorservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorservice',
            name='totalPoints',
            field=models.FloatField(default=0, verbose_name='total rate points'),
        ),
        migrations.AddField(
            model_name='doctorservice',
            name='turns',
            field=models.IntegerField(default=0, verbose_name='rate turns'),
        ),
    ]
