# Generated by Django 4.1.2 on 2022-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_doctorservice_totalpoints_doctorservice_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='method',
            field=models.TextField(blank=True, null=True, verbose_name='service method'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500, verbose_name='service description'),
        ),
    ]
