# Generated by Django 4.1.2 on 2022-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('AT_PATIENT_HOME', 'At Patient Home'), ('AT_DOCTOR_HOME', 'At Doctor Home'), ('ONLINE', 'Online'), ('CONTRACT', 'Contract')], max_length=20, verbose_name='category'),
        ),
    ]
