# Generated by Django 4.0.4 on 2022-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_securerity_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='platform',
            field=models.CharField(choices=[('MOMO', 'Momo'), ('VNPAY', 'Vnpay'), ('CASH', 'Cash'), ('SYSTEM', 'System')], default='VNPAY', max_length=20, verbose_name='platform'),
        ),
    ]
